spring.application.name=careplan-service

server.port=9004

# MongoDB — careplandb is auto-created on first document insert
spring.data.mongodb.uri=mongodb://localhost:27017/careplandb
spring.data.mongodb.database=careplandb

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# External Microservice URLs
patient.service.base-url=http://localhost:8989
healthtwin.service.base-url=http://localhost:8990
flask.service.base-url=http://localhost:5000
service.call.timeout=5000

# Logging
logging.level.com.medisphere.careplan_service=INFO
logging.level.org.springframework.data.mongodb=DEBUG