spring.application.name=config-server

server.port=8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Native file system configuration
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config