spring.application.name=patient-service

server.port=8989

# ===========================
# MongoDB
# ===========================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test

# ===========================
# Eureka
# ===========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===========================
# Logging
# ===========================
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG